repos:
  - repo: https://github.com/timothycrosley/isort
    rev: 5.5.1
    hooks:
    -   id: isort
  - repo: https://github.com/psf/black
    rev: 20.8b1 # Replace by any tag/version: https://github.com/psf/black/tags
    hooks:
      - id: black
        language_version: python3 # Should be a command that runs python3.6+
